# Generated by Django 5.2.6 on 2025-11-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dashboardstat_event_event_type_event_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="belt",
            name="color",
            field=models.CharField(default="#000000", max_length=20),
        ),
    ]
