# Generated by Django 5.2.6 on 2025-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_belt_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
