# Generated by Django 5.2.6 on 2025-11-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_eventregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="belt",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="belt",
            name="points_required",
            field=models.PositiveIntegerField(
                default=0, help_text="Points required to achieve this belt"
            ),
        ),
        migrations.AddField(
            model_name="trainee",
            name="total_points",
            field=models.PositiveIntegerField(
                default=0, help_text="Total points earned from training and events"
            ),
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Points earned (can be negative for deductions)"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("training", "Training Session Attendance"),
                            ("tournament", "Tournament Participation"),
                            ("win", "Match Win"),
                            ("seminar", "Seminar Attendance"),
                            ("admin_award", "Admin Award"),
                            ("promotion", "Belt Promotion Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_awarded",
                        to="core.event",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to="core.trainee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
